toc: false
number-sections: false

title: "Ichthyop practical session"
format:
    revealjs:
        smaller: true
        theme: [default]

    pdf:
        toc: true
        number-sections: true

author:
    - name: Christophe Lett
      orcid: 0000-0001-5809-2452
    - name: Marco Andrello
      orcid: 0000-0001-7590-2736
    - name: Nicolas Barrier
      orcid: 0000-0002-1693-4719
